version: "3"

services:
  web:
    build:
      context: .
      args:
        - DB_CONNECTION=${DB_CONNECTION}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - APP_KEY=${APP_KEY}
    ports:
      - "8090:80"
